### ISSUE TITLE
Error during parsing: unrecognized protocol option 'experimental_http3'

### ISSUE THREAD

**Issue by qualeo** [mtarld/apip-ddd#33]
**Docker/Compose Versions:**

```bash
$ docker-compose --version                                
docker-compose version 1.29.2, build unknown

docker --version        
Docker version 20.10.19+dfsg1, build d85ef84
```

**Docker Compose Config:**

```yaml
# docker-compose config | yq
services:
  caddy:
    build:
      context: /home/qualeo/Downloads/apip-ddd
      target: symfony_caddy
    depends_on:
      php:
        condition: service_started
    environment:
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeMe!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeMe!'
      SERVER_NAME: localhost, caddy:80
    ports:
      - protocol: tcp
        published: 80
        target: 80
      - protocol: tcp
        published: 443
        target: 443
      - protocol: udp
        published: 443
        target: 443
    restart: unless-stopped
    volumes:
      - caddy_config:/config:rw
      - caddy_data:/data:rw
      - /home/qualeo/Downloads/apip-ddd/docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - /home/qualeo/Downloads/apip-ddd/public:/srv/app/public:ro
      - php_socket:/var/run/php:rw
  database:
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: ChangeMe
      POSTGRES_USER: symfony
    image: postgres:13-alpine
    ports:
      - target: 5432
    volumes:
      - db-data:/var/lib/postgresql/data:rw
  php:
    build:
      args:
        SKELETON: symfony/skeleton
        STABILITY: stable
        SYMFONY_VERSION: ''
      context: /home/qualeo/Downloads/apip-ddd
      target: symfony_php
    environment:
      APP_ENV: dev
      MERCURE_JWT_SECRET: '!ChangeMe!'
      MERCURE_PUBLIC_URL: https://localhost/.well-known/mercure
      MERCURE_URL: http://caddy/.well-known/mercure
    healthcheck:
      interval: 10s
      retries: 3
      start_period: 30s
      timeout: 3s
    restart: unless-stopped
    volumes:
      - /home/qualeo/Downloads/apip-ddd:/srv/app:rw,cached
      - /srv/app/var
      - /home/qualeo/Downloads/apip-ddd/docker/php/conf.d/symfony.dev.ini:/usr/local/etc/php/conf.d/symfony.ini:rw
      - php_socket:/var/run/php:rw
version: '3.4'
volumes:
  caddy_config: {}
  caddy_data: {}
  db-data: {}
  php_socket: {}
```

**Steps to Reproduce:**
```bash
git clone https://github.com/mtarld/apip-ddd.git
cd apip-ddd
make install
# ...
  - Downloading dnoegel/php-xdg-base-dir (v0.1.1)
  - Downloading amphp/amp (v2.6.2)
  - Downloading amphp/byte-stream (v1.8.1)
  - Downloading vimeo/psalm (4.27.0)
  8/76 [==>-------------------------]  10%make[1]: *** [Makefile:52: vendor] Error 137
make: *** [Makefile:47: install] Error 2

make install
# ...
Executing script cache:clear [OK]
Executing script assets:install public [OK]

Dropped database "app" for connection named default
Created database "app" for connection named default

 Updating database schema...

     4 queries were executed

                                                                                                                        
 [OK] Database schema updated successfully!

make stop
# ...

make start
Creating apip-ddd_php_1      ... done
Creating apip-ddd_database_1 ... done
Creating apip-ddd_caddy_1    ... done

docker-compose logs -f caddy
Attaching to apip-ddd_caddy_1
# ...
caddy_1     | Error: adapting config using caddyfile: parsing caddyfile tokens for 'servers': /etc/caddy/Caddyfile:7 - Error during parsing: unrecognized protocol option 'experimental_http3'
caddy_1     | {"level":"info","ts":1667602742.0740893,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":"caddyfile"}
caddy_1     | {"level":"warn","ts":1667602742.074148,"logger":"caddyfile","msg":"DEPRECATED: protocol sub-option will be removed soon"}
caddy_1     | Error: adapting config using caddyfile: parsing caddyfile tokens for 'servers': /etc/caddy/Caddyfile:7 - Error during parsing: unrecognized protocol option 'experimental_http3'

$ docker-compose ps caddy 
      Name                    Command                 State      Ports
----------------------------------------------------------------------
apip-ddd_caddy_1   caddy run --config /etc/ca ...   Restarting  

make stop
```
